# Generated by Django 5.2.14 on 2026-07-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachback', '0004_model_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=160, unique=True)),
                ('subject_id', models.SlugField(blank=True, max_length=100)),
                ('module_id', models.SlugField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('source_kind', models.CharField(default='document', max_length=32)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='awaiting_approval', max_length=40)),
                ('approval_status', models.CharField(default='instructor_review_required', max_length=40)),
                ('extraction', models.JSONField(blank=True, default=dict)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('pipeline', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
