# Generated by Django 5.2.16 on 2026-07-20 08:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachback', '0013_adaptive_learning_runtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('domain', models.CharField(default='general', max_length=120)),
                ('learner_level', models.CharField(default='beginner', max_length=40)),
                ('safety_mode', models.CharField(default='guided', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('ready', 'ready'), ('stale', 'stale'), ('provider_failed', 'provider_failed'), ('needs_review', 'needs_review')], default='draft', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_ids', models.JSONField(blank=True, default=list)),
                ('source_anchor_ids', models.JSONField(blank=True, default=list)),
                ('source_fingerprint', models.CharField(blank=True, max_length=128)),
                ('uncertainty', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('compiler_mode', models.CharField(default='deterministic_fallback', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_packs', to='teachback.learninggoal')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'active'), ('superseded', 'superseded'), ('stale', 'stale')], default='active', max_length=32)),
                ('source_ids', models.JSONField(blank=True, default=list)),
                ('source_anchor_ids', models.JSONField(blank=True, default=list)),
                ('source_fingerprint', models.CharField(blank=True, max_length=128)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('uncertainty', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='teachback.curriculumpack')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.SlugField(max_length=160)),
                ('title', models.CharField(max_length=240)),
                ('explanation', models.TextField(blank=True, max_length=4000)),
                ('position', models.PositiveIntegerField(default=0)),
                ('source_ids', models.JSONField(blank=True, default=list)),
                ('source_anchor_ids', models.JSONField(blank=True, default=list)),
                ('uncertainty', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='teachback.curriculumversion')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(default='explain', max_length=40)),
                ('title', models.CharField(max_length=240)),
                ('prompt', models.TextField(max_length=4000)),
                ('position', models.PositiveIntegerField(default=0)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('expected_observations', models.JSONField(blank=True, default=list)),
                ('source_ids', models.JSONField(blank=True, default=list)),
                ('source_anchor_ids', models.JSONField(blank=True, default=list)),
                ('remediation_target', models.TextField(blank=True, max_length=1000)),
                ('transfer_target', models.TextField(blank=True, max_length=1000)),
                ('safety_mode', models.CharField(default='guided', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_definitions', to='teachback.conceptnode')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_definitions', to='teachback.curriculumversion')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('criteria', models.JSONField(blank=True, default=list)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('source_requirements', models.JSONField(blank=True, default=dict)),
                ('uncertainty', models.JSONField(blank=True, default=dict)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='teachback.activitydefinition')),
            ],
        ),
        migrations.CreateModel(
            name='GoalCurriculumRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='active', max_length=32)),
                ('current_position', models.PositiveIntegerField(default=1)),
                ('route', models.JSONField(blank=True, default=dict)),
                ('next_action', models.CharField(default='start_activity', max_length=120)),
                ('invalid_reason', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_goal_routes', to='teachback.activitydefinition')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_routes', to='teachback.curriculumversion')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_route', to='teachback.learninggoal')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisiteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(default='required_before', max_length=80)),
                ('confidence', models.FloatField(default=0.5)),
                ('source_anchor_ids', models.JSONField(blank=True, default=list)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_edges', to='teachback.curriculumversion')),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_prerequisites', to='teachback.conceptnode')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_prerequisites', to='teachback.conceptnode')),
            ],
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(fields=('curriculum', 'version'), name='unique_curriculum_version'),
        ),
        migrations.AddConstraint(
            model_name='conceptnode',
            constraint=models.UniqueConstraint(fields=('curriculum', 'node_key'), name='unique_curriculum_concept'),
        ),
        migrations.AddConstraint(
            model_name='prerequisiteedge',
            constraint=models.UniqueConstraint(fields=('curriculum', 'prerequisite', 'dependent'), name='unique_prerequisite_edge'),
        ),
    ]
