# Generated by Django 5.2.16 on 2026-07-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachback', '0014_curriculumpack_curriculumversion_conceptnode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningactivity',
            name='activity_type',
            field=models.CharField(choices=[('predict', 'predict'), ('explain', 'explain'), ('compare', 'compare'), ('derive', 'derive'), ('debug', 'debug'), ('analyze', 'analyze'), ('simulate', 'simulate'), ('apply', 'apply'), ('build', 'build'), ('transfer', 'transfer'), ('remediate', 'remediate')], default='explain', max_length=32),
        ),
    ]
