# Generated by Django 5.2.14 on 2026-07-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachback', '0015_alter_learningactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
