# Generated by Django 5.2.14 on 2026-07-20 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachback', '0016_learnerprofile_clerk_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_shares', to='teachback.learninggoal')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_shares', to='teachback.learnerprofile')),
            ],
        ),
    ]
