from django.urls import path
from .dynamic_views import (
    AnonymousLearnerView, AttemptClarificationView, AttemptInspectionView, AttemptLearningModeView, AttemptRecordView,
    AttemptRevisionView, CheckpointView, LearnerMemoryExportView, LearnerMemoryView, LearnerPreferencesView,
    LearnerProfileView, ModuleAttemptsView, ModuleDetailView, ModuleManifestView, RecommendationView,
    SkillEvidenceView, SubjectDetailView, SubjectListView, SubjectModulesView,
)
from .study_source_views import StudySourceDetailView, StudySourceIngestView
from .study_plan_views import ProviderStatusView, StudyPlanChatView, StudyPlanInteractionView, StudyPlanView
from .remediation_video_views import StudyRemediationVideoConfigView, StudyRemediationVideoView
from .notebook_views import (
    NotebookArtifactView,
    NotebookAskView,
    NotebookBlankNoteView,
    NotebookChatHistoryView,
    NotebookCreateView,
    NotebookDetailView,
    NotebookLessonView,
    NotebookNoteDetailView,
    NotebookNotesView,
    NotebookSourceDetailView,
    NotebookSourceRetryView,
    NotebookTextSourceView,
    NotebookSourceUploadView,
)
from .learning_os_views import (
    AccountLoginView,
    AccountLogoutView,
    AccountRegisterView,
    CsrfBootstrapView,
    CourseCohortView,
    CourseCollectionView,
    CourseDetailView,
    CourseJoinView,
    CourseSourcePackView,
    EvidenceCollectionView,
    GoalActivityAttemptView,
    GoalContractPreviewView,
    GoalCollectionView,
    GoalCurriculumView,
    GoalDetailView,
    GoalShareCreateView,
    GoalRouteView,
    GoalSourceDockView,
    InstitutionDashboardView,
    InvitationDetailView,
    MeView,
    OrganizationCollectionView,
    OrganizationMembersView,
    PrivacyView,
    ShareGrantCollectionView,
    ShareGrantDetailView,
    TeachDashboardView,
    SharedGoalDetailView,
    SharedGoalCloneView,
)

urlpatterns = [
    path("auth/csrf", CsrfBootstrapView.as_view()),
    path("auth/register", AccountRegisterView.as_view()),
    path("auth/login", AccountLoginView.as_view()),
    path("auth/logout", AccountLogoutView.as_view()),
    path("me", MeView.as_view()),
    path("workspaces", OrganizationCollectionView.as_view()),
    path("organizations", OrganizationCollectionView.as_view()),
    path("organizations/<uuid:workspace_id>/members", OrganizationMembersView.as_view()),
    path("invites/<str:token>", InvitationDetailView.as_view()),
    path("courses", CourseCollectionView.as_view()),
    path("courses/join", CourseJoinView.as_view()),
    path("courses/<uuid:course_id>", CourseDetailView.as_view()),
    path("courses/<uuid:course_id>/sources", CourseSourcePackView.as_view()),
    path("courses/<uuid:course_id>/cohort", CourseCohortView.as_view()),
    path("goals/contract-preview", GoalContractPreviewView.as_view()),
    path("goals", GoalCollectionView.as_view()),
    path("goals/<uuid:goal_id>", GoalDetailView.as_view()),
    path("goals/<uuid:goal_id>/share", GoalShareCreateView.as_view()),
    path("goals/<uuid:goal_id>/route", GoalRouteView.as_view()),
    path("goals/<uuid:goal_id>/curriculum", GoalCurriculumView.as_view()),
    path("goals/<uuid:goal_id>/sources", GoalSourceDockView.as_view()),
    path("goals/<uuid:goal_id>/attempts", GoalActivityAttemptView.as_view()),
    path("evidence", EvidenceCollectionView.as_view()),
    path("shares", ShareGrantCollectionView.as_view()),
    path("shares/<uuid:share_id>", ShareGrantDetailView.as_view()),
    path("shared-goals/<uuid:token>", SharedGoalDetailView.as_view()),
    path("shared-goals/<uuid:token>/clone", SharedGoalCloneView.as_view()),
    path("privacy", PrivacyView.as_view()),
    path("teach/dashboard", TeachDashboardView.as_view()),
    path("institution/dashboard", InstitutionDashboardView.as_view()),
    path("notebooks", NotebookCreateView.as_view()),
    path("notebooks/", NotebookCreateView.as_view()),
    path("notebooks/<uuid:notebook_id>", NotebookDetailView.as_view()),
    path("notebooks/<uuid:notebook_id>/sources", NotebookSourceUploadView.as_view()),
    path("notebooks/<uuid:notebook_id>/sources/text", NotebookTextSourceView.as_view()),
    path("notebooks/<uuid:notebook_id>/sources/<str:source_id>/retry", NotebookSourceRetryView.as_view()),
    path("notebooks/<uuid:notebook_id>/sources/<str:source_id>", NotebookSourceDetailView.as_view()),
    path("notebooks/<uuid:notebook_id>/artifacts", NotebookArtifactView.as_view()),
    path("notebooks/<uuid:notebook_id>/ask", NotebookAskView.as_view()),
    path("notebooks/<uuid:notebook_id>/chat", NotebookChatHistoryView.as_view()),
    path("notebooks/<uuid:notebook_id>/notes", NotebookNotesView.as_view()),
    path("notebooks/<uuid:notebook_id>/notes/blank", NotebookBlankNoteView.as_view()),
    path("notebooks/<uuid:notebook_id>/notes/<uuid:note_id>", NotebookNoteDetailView.as_view()),
    path("notebooks/<uuid:notebook_id>/lessons", NotebookLessonView.as_view()),
    path("study-sources/ingest", StudySourceIngestView.as_view()),
    path("study-sources/ingest/", StudySourceIngestView.as_view()),
    path("study-sources/<str:source_id>", StudySourceDetailView.as_view()),
    path("study-plans", StudyPlanView.as_view()),
    path("study-plans/", StudyPlanView.as_view()),
    path("study-plans/interactions", StudyPlanInteractionView.as_view()),
    path("study-plans/interactions/", StudyPlanInteractionView.as_view()),
    path("study-plans/chat", StudyPlanChatView.as_view()),
    path("study-plans/chat/", StudyPlanChatView.as_view()),
    path("study-plans/remediation-video", StudyRemediationVideoView.as_view()),
    path("study-plans/remediation-video/", StudyRemediationVideoView.as_view()),
    path("study-plans/remediation-video/config", StudyRemediationVideoConfigView.as_view()),
    path("study-plans/remediation-video/config/", StudyRemediationVideoConfigView.as_view()),
    path("providers", ProviderStatusView.as_view()),
    path("subjects", SubjectListView.as_view()),
    path("subjects/<slug:subject_id>", SubjectDetailView.as_view()),
    path("subjects/<slug:subject_id>/modules", SubjectModulesView.as_view()),
    path("subjects/<slug:subject_id>/modules/<slug:module_id>", ModuleDetailView.as_view()),
    path("modules/<slug:module_id>/manifest", ModuleManifestView.as_view()),
    path("modules/<slug:module_id>/attempts", ModuleAttemptsView.as_view()),
    path("modules/<slug:module_id>/attempts/", ModuleAttemptsView.as_view()),
    path("learners/anonymous", AnonymousLearnerView.as_view()),
    path("learners/<str:learner_id>/profile", LearnerProfileView.as_view()),
    path("learners/<str:learner_id>/preferences", LearnerPreferencesView.as_view()),
    path("learners/<str:learner_id>/memory", LearnerMemoryView.as_view()),
    path("learners/<str:learner_id>/memory/export", LearnerMemoryExportView.as_view()),
    path("learners/<str:learner_id>/recommendation", RecommendationView.as_view()),
    path("learners/<str:learner_id>/skills", SkillEvidenceView.as_view()),
    path("attempts/<uuid:attempt_id>/checkpoints/<slug:checkpoint_id>/predict", CheckpointView.as_view(), {"kind": "predict"}),
    path("attempts/<uuid:attempt_id>/checkpoints/<slug:checkpoint_id>/explain", CheckpointView.as_view(), {"kind": "explain"}),
    path("attempts/<uuid:attempt_id>/learning-mode", AttemptLearningModeView.as_view()),
    path("attempts/<uuid:attempt_id>/clarifications", AttemptClarificationView.as_view()),
    path("attempts/<uuid:attempt_id>/revisions", AttemptRevisionView.as_view()),
    path("attempts/<uuid:attempt_id>/record", AttemptRecordView.as_view()),
    path("attempts/<uuid:attempt_id>/inspection", AttemptInspectionView.as_view()),
]
